application: ritchietestproj
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  script: nologin.py

- url: /_ah/login_required
  script: nologin.py

- url: /hUoVeIFNIgngfTnTdlGQRg--.html
  script: scripteditor.py

- url: /js/restricted
  static_dir: static/js/restricted

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /rss.*
  script: blog.py

- url: /blogpost.*
  script: blog.py
  login: admin

- url: /blog.*
  script: blog.py

- url: /title.*
  script: scripteditor.py

- url: /sitemap.xml
  static_files: static/text/sitemap.xml
  upload: static/text/sitemap.xml

- url: /robots.txt
  static_files: static/text/robots.txt
  upload: static/text/robots.txt

- url: /convert
  static_files: html/convert.html
  upload: html/convert.html

- url: /about
  static_files: html/about.html
  upload: html/about.html

- url: /contact
  static_files: html/contact.html
  upload: html/contact.html

- url: /migration
  static_files: html/migration.html
  upload: html/migration.html

- url: /rawscripts.manifest
  static_files: rawscripts.manifest
  upload: rawscripts.manifest

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /js/min
  static_dir: static/js/min

- url: /text
  static_dir: static/text

- url: /closure-library
  static_dir: static/closure-library

- url: /editor.*
  script: nologin.py

- url: /scriptcontent.*
  script: nologin.py

- url: /bugs.*
  script: nologin.py

- url: /contactemail.*
  script: nologin.py

- url: /submitbug.*
  script: nologin.py

- url: /test.*
  script: nologin.py

- url: /save.*
  login: required
  script: nologin.py

- url: /spelldb.*
  login: admin
  script: spellcheck.py

- url: /spellcheckbigscript.*
  login: admin
  script: spellcheck.py

- url: /spellcheck.*
  script: spellcheck.py

- url: /revision.*
  login: required
  script: revisionhistory.py

- url: /junkparse.*
  login: admin
  script: deletetasks.py

- url: /automateddelete.*
  login: admin
  script: deletetasks.py

- url: /notes.*
  login: required
  script: notes.py

- url: /onescript.*
  login: admin
  script: scripteditor.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  login: admin
  script: stats.py

- url: /.*
  login: required
  script: scripteditor.py