application: ritchietestproj
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  script: nologin.py

- url: /_ah/login_required
  script: nologin.py

- url: /convert
  static_files: convert.html
  upload: convert.html

- url: /about
  static_files: about.html
  upload: about.html

- url: /blog
  static_files: blog.html
  upload: blog.html

- url: /contact
  static_files: contact.html
  upload: contact.html

- url: /migration
  static_files: migration.html
  upload: migration.html

- url: /rawscripts.manifest
  static_files: rawscripts.manifest
  upload: rawscripts.manifest

- url: /js/restricted
  static_dir: static/js
  login: admin

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /js/min
  static_dir: static/js/min

- url: /text
  static_dir: static/text

- url: /editor.*
  script: nologin.py

- url: /scriptcontent.*
  script: nologin.py

- url: /bugs.*
  script: nologin.py

- url: /contactemail.*
  script: nologin.py

- url: /submitbug.*
  script: nologin.py

- url: /test.*
  script: nologin.py

- url: /save.*
  login: required
  script: nologin.py

- url: /spelldb.*
  login: admin
  script: spellcheck.py

- url: /spellcheckbigscript.*
  login: admin
  script: spellcheck.py

- url: /spellcheck.*
  script: spellcheck.py

- url: /revision.*
  login: required
  script: revisionhistory.py

- url: /titlepage.*
  script: scripteditor.py

- url: /junkparse.*
  login: admin
  script: deletetasks.py

- url: /automateddelete.*
  login: admin
  script: deletetasks.py

- url: /notes.*
  login: required
  script: notes.py

- url: /onescript.*
  login: admin
  script: scripteditor.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  login: required
  script: scripteditor.py

